apiVersion: v1
appVersion: "1.0"
description: A Helm chart for a sample app  using IBM's Botkit middleware
name: k8s-watson-botkit-example
version: "1.0.3"
maintainers:
  - name: David Carew
    email: carew@us.ibm.com
keywords:
  - Watson
  - Botkit
  - Other
  - Sample
icon: https://www.ibm.com/watson/assets/duo/img/common/avatar_purple.png
sources:
  - https://github.com/djccarew/app-modernization-botkit-lab
