replicas:
 __metadata:
    name: "replicas"
    label: "Number of replicas"
    description: "The number of desired replica pods that run simultaneously."
    type: "number"
    immutable: false
    required: true
