apiVersion: v1
entries:
  k8s-watson-botkit-example:
  - apiVersion: v1
    appVersion: "1.0"
    created: 2019-01-12T03:59:09.005424-06:00
    description: A Helm chart for a sample app  using IBM's Botkit middleware
    digest: 71f1652505b232435d71fcb450670683b753c0e1402c1470f9a8633b84ec46f3
    icon: https://www.ibm.com/watson/assets/duo/img/common/avatar_purple.png
    keywords:
    - Watson
    - Botkit
    - Other
    - Sample
    maintainers:
    - email: carew@us.ibm.com
      name: David Carew
    name: k8s-watson-botkit-example
    sources:
    - https://github.com/djccarew/app-modernization-botkit-lab
    urls:
    - https://djccarew.github.io/app-modernization-botkit-lab/chart/k8s-watson-botkit-example-1.0.tgz
    version: "1.0"
generated: 2019-01-12T03:59:09.003582-06:00
