apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: k8s-watson-botkit
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name | quote }}


spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
         app: k8s-watson-botkit
         chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
         release: {{ .Release.Name | quote }}


    spec:
      containers:
      - name: {{ .Release.Name }}-web
        image: "djccarew/watson-assistant-botkit-example:1.0"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: DEBUG_MODE
          value: "{{ .Values.debugMode }}"
        - name: ASSISTANT_IAM_APIKEY
          value: {{ .Values.watsonskill.assistantIamApiKey }}
        - name: SLACK_TOKEN
          value:  {{ .Values.slackauth.slackToken }}
        - name: SLACK_SIGNING_SECRET
          value: {{ .Values.slackauth.slackSigningSecret }}
        - name: WORKSPACE_ID
          value: {{ .Values.watsonskill.workspaceId }}
        - name: ASSISTANT_URL
          value: "{{ .Values.watsonskill.assistantUrl }}"
